### ISSUE TITLE
Image not displaying after deployment

### ISSUE THREAD

**Issue by gdcho** [MiSaengg/2800-202310BBY19#23]
sf2.png - 39.68 mb
horror.png - 5.32 mb

sf2.png results in 404 error after deployment, while horror.png displays. The error may be due to image size.

**Comment by jasper-oh** [comment]
Sorry for confusion, the file size isn't matter. i think the file name is the problem. So I change it to sf2.png -> sifi.png and it works!

**Comment by jasper-oh** [comment]
Thanks for sharing the issue!
