### ISSUE TITLE
Complete & incomplete colour different design feedback 🔥

### ISSUE THREAD

**Issue by jasper-oh** [MiSaengg/2800-202310BBY19#28]
Complete & incomplete colour different design feedback 🔥
<img width="467" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/b7ff1e28-840e-420c-b9da-91fd8ff01494">

**Comment by gdcho** [comment]
Hi Jasper, how would you like it if Complete was green/blue and Incomplete was yellow?

**Comment by jasper-oh** [comment]
Yes master, dobby will work on it
