### ISSUE TITLE
Spike issue

### ISSUE THREAD

**Issue by noelkim4924** [MiSaengg/2800-202310BBY19#36]
The server went down due to a spark in MongoDB when writing  at the branch thread for a minute with a maximum connection of 500 megabytes.
<img width="1177" alt="Screenshot 2023-05-17 at 11 52 49 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/122150422/983da627-fbad-4ef1-8969-06341b89f828">

**Comment by gdcho** [comment]
ChatGPT Reponse:
If you're seeing a connection spike specifically when creating a new "branchThread", it could be because the createBranchThread function is making multiple database queries in sequence:

    Finding the mainThread where the id is mainThreadId.
    Creating a new branchThread.
    Updating the mainThread with the new phaseStage.

Each of these operations could open a new connection to your MongoDB database, which could contribute to your connection spike. However, note that Prisma uses connection pooling by default, which means it should reuse database connections where possible, rather than opening a new connection for each query.

**Comment by gdcho** [comment]
Maybe we can add disconnect to clean up connections to the database after creating a branch thread
```sh
// At the end of your function
await prisma.$disconnect();
```

**Comment by gdcho** [comment]
Updates (05/18):
Spikes on AI generating for branchThread
(Code in app/components/modal/Modal.jsx

**Comment by gdcho** [comment]
If you're noticing a spike in your database connections and you're getting a 500 error, it's possible that your server-side logic or your client-side requests could be causing the problem. Here are some potential causes and possible solutions:

    Multiple Client-Side Requests: If your React components are making many simultaneous requests to your server, this could cause a spike in your database connections. Ensure your React components aren't making unnecessary requests, especially in rapid succession.

    Connection Management: When you're done with a database connection, it's important to close it. If you're using Prisma, it will handle connection pooling for you, but in some serverless environments, it's important to manually disconnect when you're done.

    Inefficient Server-Side Code: If your server-side logic makes many database queries for each request, this could cause a connection spike. Check your server-side code to ensure you're not making unnecessary database queries.

**Comment by gdcho** [comment]
Changed useEffect code to add dependency array with ones without it.

**Comment by gdcho** [comment]
Fixed: Remember to use dependency array in useEffect 
Reference: https://stackoverflow.com/questions/53243203/react-hook-useeffect-runs-continuously-forever-infinite-loop

**Comment by gdcho** [comment]
Stabilized under 250 megabytes
![image](https://github.com/MiSaengg/2800-202310BBY19/assets/48280799/c0ef64b5-d65c-4ec3-8da7-c0fc92ee4d8e)

**Comment by gdcho** [comment]
<img width="857" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/48280799/c30f8045-e025-46a8-9951-6295a0100112">

Looking good!
