### ISSUE TITLE
Uncertain error

### ISSUE THREAD

**Issue by noelkim4924** [MiSaengg/2800-202310BBY19#38]
When we try to submit in the branch thread and refresh the page, suddenly an error pops up and disappears suddenly.

<img width="1229" alt="Screenshot 2023-05-18 at 1 34 18 AM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/122150422/7a2d5a95-a0c3-4d7b-90c5-4498c45ddf05">

**Comment by jasper-oh** [comment]
Ill fix

**Comment by jasper-oh** [comment]
Error solved! Thanks for the sharing this issue. 

This issue is solved by handling backend api code little bit.

```javascript
 if (size < 3) {
      const updatedPhaseStage = await prisma.mainThread.update({
        where: {
          id: mainThreadId,
        },
        data: {
          phaseStage: phaseStage,
        },
      });
    } else {
      return { error: "You can't create more than 3 branches." };
    }
    
    return { threadFromDB };
``` 

Thanks again
