### ISSUE TITLE
BUG ISSUE - Cannot create additional branch if there are already two

### ISSUE THREAD

**Issue by gdcho** [MiSaengg/2800-202310BBY19#42]
Original code in lib/prisma/branchThread
```sh
if (size < 3) {
      const updatedPhaseStage = await prisma.mainThread.update({
        where: {
          id: mainThreadId,
        },
        data: {
          phaseStage: phaseStage,
        },
      });
    } else {
      return { error: "You can't create more than 3 branches." };
    }
```
Prevents creation of branch if there are 3 branch thread objects existing in phaseStage object array.

**Comment by jasper-oh** [comment]
Yeah seems like we have an issue in that code

So the specific issue is can't put the branchThread in the MainThread phaseStage index if there is 2 indexes in the phaseStage 
Is it clear?

**Comment by gdcho** [comment]
Yes, if two users try to create a new branch at the same time, it could result in more than three branches, even if the condition size <= 3 is checked. This problem is often referred to as a race condition, where the system's behavior is dependent on the sequence or timing of other uncontrollable events.
Any ideas for that?

**Comment by gdcho** [comment]
@jasper-oh 
What do you think of: https://www.prisma.io/docs/concepts/components/prisma-client/transactions

**Comment by jasper-oh** [comment]
Ok it seems like simultaneous transaction issue. Let me check and give ya some comments asap. Thanks for sharing link.

**Comment by gdcho** [comment]
I think it worked, here is the code
```sh
export async function createBranchThread(thread, mainThreadId) {
  try {
    await prisma.$transaction(async (prisma) => {
      const mainThread = await prisma.mainThread.findUnique({
        where: {
          id: mainThreadId,
        },
      });

      const threadFromDB = await prisma.branchThread.create({ data: thread });

      const phaseStage = mainThread.phaseStage || {};
      phaseStage[threadFromDB.id] = threadFromDB;
      const size = Object.keys(phaseStage).length;

      if (size <= 3) {
        const updatedPhaseStage = await prisma.mainThread.update({
          where: {
            id: mainThreadId,
          },
          data: {
            phaseStage: phaseStage,
          },
        });
        return { updatedPhaseStage };
      } else {
        throw new Error("You can't create more than 3 branches.");
      }
    });
  } catch (error) {
    return { error };
  }
}
```
We can run more tests when we meet

**Comment by jasper-oh** [comment]
Nicely done @gdcho  appreciated
