### ISSUE TITLE
BUG ISSUE - Reload button does not update 

### ISSUE THREAD

**Issue by gdcho** [MiSaengg/2800-202310BBY19#43]
When first accessing thread home page:
<img width="322" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/48280799/291bb44f-5608-4faf-87fe-32ab9946e969">

After pressing reload button on bottom right:
<img width="322" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/48280799/43283294-ba76-4499-afa9-dc0b4e58ab22">

Notice how everything else changes but the user pen name

**Comment by gdcho** [comment]
The problem only seems to be with reload button since when reloading the page on browser changes the user pen name as well.

**Comment by jasper-oh** [comment]
Working on it!

**Comment by jasper-oh** [comment]
Fixed!
how?  Add a relational database user in MainThread
<img width="805" alt="Screenshot 2023-05-18 at 4 21 19 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/ce130f17-3ec9-4ef7-bba7-9196c27ee597">

**Comment by gdcho** [comment]
Amazing work! Good job
