### ISSUE TITLE
MainThread owners for merging branches

### ISSUE THREAD

**Issue by gdcho** [MiSaengg/2800-202310BBY19#45]
Should we include a dialog that confirms mainThread user's actions of merging the branch thread into the main thread to prevent accidental click?
We should discuss more about this.

**Comment by gdcho** [comment]
I don't think it should be an issue for branch thread, since the users would make the branch thread can delete their own submissions, but if the branch is merged, there is no way to revert that as the user.

**Comment by jasper-oh** [comment]
Good comment so I think we need to put alerts in certain page after the action. Can you work on this function?

**Comment by gdcho** [comment]
Got it, working on it

**Comment by gdcho** [comment]
Added window dialog:
```sh
 const deleteBranchThread = async (e) => {
    e.preventDefault();
    const confirmed = window.confirm(
      "Are you sure you want to delete?"
    );
    if (confirmed) {
//rest of delete logic
}

**Comment by jasper-oh** [comment]
Nicely Done! 🙌
