### ISSUE TITLE
All mandatory fields (e.g. Title, Genre, MainThread) should be indicated by an asterisk (or something like that). 

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#65]
Please include an asterisk.

**Comment by jasper-oh** [comment]
Can you check this image?
<img width="1010" alt="Screenshot 2023-05-24 at 12 31 11 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/59d0cd66-bac4-4521-80c6-ec55ceba59df">
