### ISSUE TITLE
Dropdown fields should have the first entry as blank or text like "Select".

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#66]
<img width="169" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/4d7d569c-a16c-434c-8971-ef29459dd176">

Sifi -> Sci-Fi

**Comment by jasper-oh** [comment]
<img width="994" alt="Screenshot 2023-05-24 at 12 39 27 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/fdc94208-7eaa-4e94-8ecc-5865422d3bac">
Can you look this image?
