### ISSUE TITLE
"Threads" and "Stories" are used interchangeably.

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#67]
"Threads" and "Stories" are used interchangeably.
It confuses some users.

<img width="432" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/71e11761-19c7-4592-8456-f4788f9ec468">

**Comment by jasper-oh** [comment]
<img width="1007" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/32ae04d9-6ac6-4d62-9152-f14a578319fa">
<img width="993" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/bf17f158-524b-4da6-abbc-639af1a935bc">
Can you check these image?
