### ISSUE TITLE
All input fields should check for special characters.

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#70]
When users are creating a new thread, it should not allow users to type in special characters.

**Comment by jasper-oh** [comment]
I'm working on only validate the title value for not using special characters.

**Comment by jasper-oh** [comment]
<img width="982" alt="Screenshot 2023-05-24 at 1 06 51 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/81265799-1917-42a9-bce4-7e5a8ba8bfd8">

we decided to allow using special characters in title. but set a limit number of letters in title (1-100)
