### ISSUE TITLE
Cards on the main thread page should be aligned properly.

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#72]
<img width="487" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/d81d3691-aeef-449f-b17d-f695411e6266">

**Comment by jasper-oh** [comment]
<img width="425" alt="Screenshot 2023-05-24 at 1 58 02 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/b21303f0-6b76-4943-a4af-d89294cb917e">
Can you check this image?
