### ISSUE TITLE
All the texts on the app should be easy to read.

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#73]
<img width="492" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/b2a81d96-f82d-4414-91f5-e5f1bef267af">

**Comment by jasper-oh** [comment]
<img width="439" alt="Screenshot 2023-05-24 at 3 11 30 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/5a7d73c5-4bb8-4628-a7b0-41742434c3f5">
Can you look it up? thanks!
