### ISSUE TITLE
Appropriate fields are highlighted in case of errors

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#74]
The "title" input fileld should be highlighted only when there is an error (e.g. empty field). 

Other fields should be highlighted in case of errors.

<img width="480" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/9e544c2d-cb59-479d-b77f-41b414c724dc">

**Comment by jasper-oh** [comment]
<img width="423" alt="Screenshot 2023-05-24 at 3 26 17 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/a5db40d2-a073-4593-9075-75116034d166">
I deleted the red outline and we are just using the alert that provided html just like below.
<img width="429" alt="Screenshot 2023-05-24 at 3 27 23 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/aa1476d8-e54f-4086-8428-d1900ca7d602">
