### ISSUE TITLE
Confirmation messages should be displayed before performing any update.

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#75]
A confirmation message is missing when submitting a new thread or branch tread.

(But, when clicked "delete" button, a confirmation message pops up)

<img width="470" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/b4633a87-3125-4870-98a7-519c245bc0f5">

<img width="484" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/7a912cf6-ebfc-45fd-913d-d39d5fd5aeb5">

**Comment by jasper-oh** [comment]
<img width="537" alt="Screenshot 2023-05-24 at 3 32 36 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/4f5c408a-85ae-44d7-85be-da9b91270370">
<img width="475" alt="Screenshot 2023-05-24 at 3 48 11 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/10c52167-d8ee-480f-a396-4055bc6d3c33">
