### ISSUE TITLE
"Submit" and "Upload" are used interchangeably.

### ISSUE THREAD

**Issue by jchung7v** [MiSaengg/2800-202310BBY19#76]
<img width="469" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/0740c87e-ca33-4b2d-997a-be193c8af348">

<img width="476" alt="image" src="https://github.com/MiSaengg/2800-202310BBY19/assets/111412548/7701527a-fb4c-4cdf-bf12-1e61d5e7978e">

**Comment by jasper-oh** [comment]
<img width="420" alt="Screenshot 2023-05-24 at 3 49 54 PM" src="https://github.com/MiSaengg/2800-202310BBY19/assets/63331153/954666e8-8ebc-433e-b7b0-3e6bfbe8ab23">
Unify to Upload!
